#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_FREditorTYPE                130
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        205
#define ID_VIEW_APPLOOK_OFF_XP          206
#define ID_VIEW_APPLOOK_WIN_XP          207
#define ID_VIEW_APPLOOK_OFF_2003        208
#define ID_VIEW_APPLOOK_VS_2005         209
#define ID_VIEW_APPLOOK_VS_2008         210
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define ID_VIEW_APPLOOK_WINDOWS_7       219
#define IDD_ROOTDLG                     310
#define IDD_CHARACTER                   312
#define IDD_MULTISPRITE                 314
#define IDD_ANIMATION                   316
#define IDD_ANISPRITELIST               318
#define IDD_ANIMATIONLIST               319
#define IDD_NEWMULTISPRITE              322
#define IDD_TEXTURELIST                 324
#define IDD_MULTISPRITELIST             326
#define IDD_DIALOG1                     328
#define IDD_CHARSTAT                    330
#define IDD_MONSTAT                     331
#define IDD_STATDLG                     338
#define IDD_EFFECTDLG                   340
#define IDD_EFFECT                      340
#define IDD_DIALOG2                     342
#define IDD_SKILLDLG                    342
#define IDD_ACTIONSCRIPT                344
#define IDD_SKILLDATADLG                345
#define IDD_DIALOG3                     348
#define IDD_MAPDLG                      348
#define IDD_DIALOG4                     350
#define IDC_TAB1                        1000
#define IDC_SPRITECHECK                 1001
#define IDC_ANICHECK                    1002
#define IDC_LIST1                       1003
#define IDC_COMBO1                      1004
#define IDC_SPRITEKEY2                  1005
#define IDC_SPRITEKEY1                  1006
#define IDC_OUTSPRITENAME               1007
#define IDC_STARTPOSX                   1008
#define IDC_STARTPOSY                   1009
#define IDC_SAVEBUTTON                  1010
#define IDC_CREATEBUTTON                1011
#define IDC_SIZEY                       1012
#define IDC_SIZEX                       1013
#define IDC_PIVOTX                      1014
#define IDC_ROW                         1015
#define IDC_FRAMECOUNT                  1016
#define IDC_COLM                        1017
#define IDC_PIVOTY                      1018
#define IDC_SAVESPRITELIST              1019
#define IDC_TYPECOMBO                   1020
#define IDC_ANIMATIONEDIT               1021
#define IDC_BASECHECK                   1022
#define IDC_CYCLECHECK                  1023
#define IDC_LOOPCHECK                   1024
#define IDC_ANISPRITENAME               1025
#define IDC_BLACKBACKCHECK              1025
#define IDC_FULLSTART                   1026
#define IDC_BLACKBACKCHECK2             1026
#define IDC_FIXPOS                      1026
#define IDC_FULLEND                     1027
#define IDC_REPEATSTART                 1028
#define IDC_REPEATEND                   1029
#define IDC_ANIMATIONCOUNT              1030
#define IDC_FBASEINTERVAL               1031
#define IDC_RBASEINTERVAL               1032
#define IDC_BUTTON1                     1033
#define IDC_REGISTERBUTTON              1033
#define IDC_SPRITEDELETEBUTTON          1033
#define IDC_CSTATCREATEBUTTON           1033
#define IDC_SOUNDADDBUTTON              1033
#define IDC_ACTCREATEBUTTON             1033
#define IDC_LEVELREGBUTTON              1033
#define IDC_TILELOADBUTTON              1033
#define IDC_BUTTON2                     1034
#define IDC_DETAILSETTINGBUTTON         1034
#define IDC_SPRITEREGISTERBUTTON        1034
#define IDC_CSTATDELETEBUTTON           1034
#define IDC_SOUNDDELBUTTON              1034
#define IDC_ACTDELETEBUTTON             1034
#define IDC_LEVELDELBUTTON              1034
#define IDC_TILESAVEBUTTON              1034
#define IDC_ALLSAVEBUTTON               1035
#define IDC_SOUNDTIMEBUTTON             1035
#define IDC_COSTREGBUTTON               1035
#define IDC_OBJECTLOADBUTTON            1035
#define IDC_DELETEBUTTON                1036
#define IDC_ANIDELETEBUTTON             1036
#define IDC_SOUNDPLAY                   1036
#define IDC_COSTDELBUTTON               1036
#define IDC_OBJECTSAVEBUTTON4           1036
#define IDC_OBJECTSAVEBUTTON            1036
#define IDC_ANIFRAMELIST                1037
#define IDC_HITREGBUTTON                1037
#define IDC_STARTFRAME                  1038
#define IDC_HITDELBUTTON                1038
#define IDC_MULTISPRITETAB              1039
#define IDC_FOLDERCOM                   1040
#define IDC_TEXTURELIST                 1041
#define IDC_MULTISPRITENAME             1042
#define IDC_NEWSTARTPOSX                1043
#define IDC_NEWSTARTPOSY                1044
#define IDC_NEWSIZEX                    1045
#define IDC_EDIT5                       1046
#define IDC_NEWSIZEY                    1046
#define IDC_YCOUNT                      1047
#define IDC_XCOUNT                      1048
#define IDC_NEWFRAMECOUNT               1049
#define IDC_NEWPIVOTY                   1051
#define IDC_NEWPIVOTX                   1052
#define IDC_SPRITESAVEBUTTON            1053
#define IDC_MULTISPRITELIST             1054
#define IDC_LOADBUTTON                  1055
#define IDC_SPRITELOADBUTTON            1055
#define IDC_BUTTON3                     1056
#define IDC_ANIMATIONLOADNUTTON         1056
#define IDC_CSTATLOADBUTTON             1056
#define IDC_EFFECTCREATEBUTTON          1056
#define IDC_ACTLOADBUTTON               1056
#define IDC_SKILLDATACREATEBUTTON       1056
#define IDC_EFFECTDELETEBUTTON          1057
#define IDC_SKILLDATADELETEBUTTON       1057
#define IDC_TAB2                        1058
#define IDC_EFFECTLOADBUTTON2           1058
#define IDC_EFFECTLOADBUTTON            1058
#define IDC_SDSKILLLOADEBUTTON          1058
#define IDC_EFFECTSAVEBUTTON            1059
#define IDC_SDSKILLSAVEEBUTTON          1059
#define IDC_STATTAB                     1060
#define IDC_LEVELSLIDER                 1061
#define IDC_CSTATSAVEBUTTON             1062
#define IDC_MAINSTAT                    1063
#define IDC_STR                         1064
#define IDC_DEX                         1065
#define IDC_INT                         1066
#define IDC_LUK                         1067
#define IDC_DEMAGE                      1068
#define IDC_DEF                         1069
#define IDC_HP                          1070
#define IDC_MP                          1071
#define IDC_CRITICAL                    1072
#define IDC_CRITICALDEMAGE              1073
#define IDC_DEMAGERANGE                 1074
#define IDC_AVOIDABILITY                1075
#define IDC_STATCHARLIST                1076
#define IDC_EFFECTLISTCOM               1077
#define IDC_EFFECTLIST                  1078
#define IDC_EFFECTANINAME               1079
#define IDC_EFFECTNAME                  1080
#define IDC_SOUNDCOMBO                  1081
#define IDC_STARTTIME                   1082
#define IDC_EFFECTLIFETIME              1083
#define IDC_CUSTONSIZEX                 1084
#define IDC_IMAGEMAG                    1085
#define IDC_IMAGETIME                   1086
#define IDC_LAYERCOMBO                  1087
#define IDC_SELECTSOUND                 1090
#define IDC_CUSTONSIZEY                 1091
#define IDC_EFFECTNUMBER                1092
#define IDC_ACTSAVEBUTTON               1093
#define IDC_ACTSKILLNO                  1094
#define IDC_EDIT2                       1095
#define IDC_ANIREGCOMBO                 1096
#define IDC_SOUNDREGCOMBO               1097
#define IDC_ANICOMBO                    1098
#define IDC_MOVEREGCOMBO                1099
#define IDC_ANISTARTTIME                1100
#define IDC_SOUNDSTARTTIME              1101
#define IDC_ANIREGBUTTON                1102
#define IDC_SOUNDREGBUTTON              1103
#define IDC_ANIDELBUTTON                1104
#define IDC_ANISOUNDDELBUTTON           1105
#define IDC_MOVECOMBO                   1106
#define IDC_MOVEREGBUTTON               1107
#define IDC_MOVEDELBUTTON               1108
#define IDC_CMOVESTARTTIME              1109
#define IDC_CMOVEENDTIME                1110
#define IDC_CMOVEHIDETIME               1111
#define IDC_CMOVESTARTPOSX              1112
#define IDC_CMOVESTARTPOSY              1113
#define IDC_CMOVEENDPOSX                1114
#define IDC_CMOVEENDPOSY                1115
#define IDC_ACTSKILLEFFECTREGCOMBO      1116
#define IDC_ACTSKILLEFFECTCOMBO         1117
#define IDC_ACTSKILLEFFECTREGBUTTON     1118
#define IDC_ACTSKILLEFFECTDELBUTTON     1119
#define IDC_ACTSKILLEFFECTPOSCOMBO      1120
#define IDC_ACTSKILLEFFECTPOSX          1121
#define IDC_ACTSKILLEFFECTPOSY          1122
#define IDC_ACTSKILLEFFECTSTARTTIME     1123
#define IDC_ACTSKILLEFFECTSIZEX         1124
#define IDC_ACTSKILLEFFECTSIZEY         1125
#define IDC_ACTSKILLEFFECTMAG           1126
#define IDC_ACTSKILLEFFECTMOVECOMBO     1127
#define IDC_ACTSKILLEFFECTMOVESTARTTIME 1128
#define IDC_ACTSKILLEFFECTMOVETIME      1129
#define IDC_ACTSKILLEFFECTHIDETIME      1130
#define IDC_ACTSKILLEFFECTMOVESTARTPOSX 1131
#define IDC_ACTSKILLEFFECTMOVESTARTPOSY 1132
#define IDC_ACTSKILLEFFECTMOVEENDPOSX   1133
#define IDC_ACTSKILLEFFECTMOVEENDPOSX2  1134
#define IDC_SCENEEFFECTREGCOMBO         1135
#define IDC_SCENEEFFECTCOMBO            1136
#define IDC_DETAILSCENEEFFECTCOMBO      1137
#define IDC_SCENEEFFECTSTARTTIME        1138
#define IDC_SCENEEFFECTACTTIME          1139
#define IDC_SCENEEFFECTSUBTIME          1140
#define IDC_ZOOMPOSCOMBO                1141
#define IDC_ZOOMPOSX                    1142
#define IDC_ZOOMPOSX2                   1143
#define IDC_ZOOMNEAR                    1144
#define IDC_ZOOMFAR                     1145
#define IDC_CAMEFFECTREGBUTTON          1146
#define IDC_CAMEFFECTREGBUTTON2         1147
#define IDC_CAMEFFECTDELBUTTON          1147
#define IDC_LIST2                       1147
#define IDC_SKILLDATA_SKILLNO           1149
#define IDC_SKILLDATA_CHARCOM           1150
#define IDC_SDTOTALTIMEEDIT             1151
#define IDC_SKILLTYPECOM                1152
#define IDC_BUFFTYPECOM                 1153
#define IDC_TEAMTARGETCOM               1154
#define IDC_ENEMYTARGETCOM              1155
#define IDC_INITCHARPOSCOM              1156
#define IDC_CHARFIXPOSXEDIT             1157
#define IDC_CHARFIXPOSYEDIT             1158
#define IDC_CHARPOSPIVOTXEDIT           1159
#define IDC_CHARPOSPIVOTYEDIT           1160
#define IDC_SKILLLEVELCOM               1161
#define IDC_SKILLCOUNTEDIT              1162
#define IDC_SKILLLCOSTCOM               1163
#define IDC_SKILLCOSTEDIT               1164
#define IDC_DEMAGESTYLECOM              1165
#define IDC_OPTIONSLIDER                1166
#define IDC_HITDATACOM                  1167
#define IDC_TILEMAPCOM                  1167
#define IDC_HITSTARTTIMEEDIT            1168
#define IDC_TILERADIO                   1168
#define IDC_CURHITDATACOUNTEDIT         1169
#define IDC_OBJECTRADIO                 1169
#define IDC_HITCOUNTEDIT                1170
#define IDC_TILETYPECOM                 1170
#define IDC_SDHITEFFECTCOM              1171
#define IDC_TILEOPTIONCOM               1171
#define IDC_DEMAGEMAGEDIT               1172
#define IDC_TILEINDEXXEDIT              1172
#define IDC_FIXDEMAGEEDIT               1173
#define IDC_TILEINDEXYEDIT              1173
#define IDC_DEMAGEFONTMAGEDIT           1174
#define IDC_EDIT1                       1174
#define IDC_EFFECTPOSMODECOM            1175
#define IDC_MAPOBJECTCOMBO              1175
#define IDC_HITEFFECTPOSPIVOTXEDIT      1176
#define IDC_MAPOBJECTNO                 1176
#define IDC_HITEFFECTPOSPIVOTYEDIT      1177
#define IDC_MAPOBJECTSIZE               1177
#define IDC_HITEFFEIMAGEMAGEDIT         1178
#define IDC_HITEFFETSIZEXEDIT           1179
#define IDC_HITEFFETSIZEYEDIT           1180
#define IDC_HITSOUNDCOM                 1181
#define IDC_HITREACTIONCOM              1182
#define IDC_BUFFDETAILTYPECOM           1183
#define IDC_BUFFVALUEEDIT               1184
#define IDC_BUFFTURNCOUNTEDIT           1185
#define IDC_BUFFICONCOM                 1186
#define IDC_BUFFEFFECTCOM               1187

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        352
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1176
#define _APS_NEXT_SYMED_VALUE           310
#endif
#endif
